import { EventType, TicketsStatus } from "./types";

export const EVENTS: EventType[] = [
  {
    id: "1",
    title: "Tiefblaue Nacht @ Bootshaus Blckbx",
    date: "Fr. 05.05.2023",
    time: "23:00 Uhr",
    location: "Bootshaus (Blckbx), Köln",
    tickets: "15,00 Euro",
    info: "Test Info",
    ticketsStatus: TicketsStatus.AVAILABLE,
    coverUrl: "/tiefblauenacht.jpeg",
  },
  {
    id: "2",
    title: "Tiefblaue Nacht @ Bootshaus Blckbx",
    date: "Fr. 05.05.2023",
    time: "23:00 Uhr",
    location: "Bootshaus (Blckbx), Köln",
    tickets: "15,00 Euro",
    info: "Test Info",
    ticketsStatus: TicketsStatus.AVAILABLE,
    coverUrl: "/tiefblauenacht.jpeg",
  },
  {
    id: "3",
    title: "Tiefblaue Nacht @ Bootshaus Blckbx",
    date: "Fr. 05.05.2023",
    time: "23:00 Uhr",
    location: "Bootshaus (Blckbx), Köln",
    tickets: "15,00 Euro",
    info: "Test Info",
    ticketsStatus: TicketsStatus.AVAILABLE,
    coverUrl: "/tiefblauenacht.jpeg",
  },
  {
    id: "4",
    title: "Tiefblaue Nacht @ Bootshaus Blckbx",
    date: "Fr. 05.05.2023",
    time: "23:00 Uhr",
    location: "Bootshaus (Blckbx), Köln",
    tickets: "15,00 Euro",
    info: "Test Info",
    ticketsStatus: TicketsStatus.AVAILABLE,
    coverUrl: "/tiefblauenacht.jpeg",
  },
];
